# Generated by Django 5.1.1 on 2025-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
