# Generated by Django 5.1.1 on 2025-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='define',
            field=models.CharField(default='blog', max_length=100),
        ),
    ]
