# Generated by Django 5.1.1 on 2025-07-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HappyBlogs', '0002_blogs_define'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='define',
        ),
    ]
